In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r'C:\Users\RITODEEP\Downloads\dataset\train_.csv',encoding='latin-1',nrows=70000)

In [4]:
df

,Unnamed: 0,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1,2,15706,320,50,1722,0,35,-1,79
1,1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1,0,15704,320,50,1722,0,35,100084,79
2,2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1,0,15704,320,50,1722,0,35,100084,79
3,3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1,0,15706,320,50,1722,0,35,100084,79
4,4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,...,1,0,18993,320,50,2161,0,35,-1,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,69995,3.129585e+18,0,14102100,1005,1,5ee41ff2,17d996e6,f028772b,ecad2386,...,1,0,16920,320,50,1899,0,431,100081,117
69996,69996,3.129652e+18,1,14102100,1005,1,d9750ee7,98572c79,f028772b,ecad2386,...,1,0,17614,320,50,1993,2,1063,100084,33
69997,69997,3.129855e+18,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1,0,15706,320,50,1722,0,35,-1,79
69998,69998,3.129902e+18,0,14102100,1005,0,543a539e,c7ca3108,3e814130,ecad2386,...,1,0,20352,320,50,2333,0,39,-1,157
69999,69999,3.129955e+18,0,14102100,1005,0,5b08c53b,7687a86e,3e814130,ecad2386,...,1,0,17654,300,250,1994,2,39,-1,33

In [5]:
print(df.isnull().sum())
df.isnull().sum().sum()

Unnamed: 0          0
id                  0
click               0
hour                0
C1                  0
banner_pos          0
site_id             0
site_domain         0
site_category       0
app_id              0
app_domain          0
app_category        0
device_id           0
device_ip           0
device_model        0
device_type         0
device_conn_type    0
C14                 0
C15                 0
C16                 0
C17                 0
C18                 0
C19                 0
C20                 0
C21                 0
dtype: int64

0

In [6]:
df["tstamp"] = pd.to_datetime(df["hour"], format="%y%m%d%H")
df["year"] = df["tstamp"].dt.year
df["month"] = df["tstamp"].dt.month
df["day"] = df["tstamp"].dt.day
df["hours"] = df["tstamp"].dt.hour
df

,Unnamed: 0,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,...,C17,C18,C19,C20,C21,tstamp,year,month,day,hours
0,0,1.000009e+18,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1722,0,35,-1,79,2014-10-21,2014,10,21,0
1,1,1.000017e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1722,0,35,100084,79,2014-10-21,2014,10,21,0
2,2,1.000037e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1722,0,35,100084,79,2014-10-21,2014,10,21,0
3,3,1.000064e+19,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1722,0,35,100084,79,2014-10-21,2014,10,21,0
4,4,1.000068e+19,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,...,2161,0,35,-1,157,2014-10-21,2014,10,21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,69995,3.129585e+18,0,14102100,1005,1,5ee41ff2,17d996e6,f028772b,ecad2386,...,1899,0,431,100081,117,2014-10-21,2014,10,21,0
69996,69996,3.129652e+18,1,14102100,1005,1,d9750ee7,98572c79,f028772b,ecad2386,...,1993,2,1063,100084,33,2014-10-21,2014,10,21,0
69997,69997,3.129855e+18,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,...,1722,0,35,-1,79,2014-10-21,2014,10,21,0
69998,69998,3.129902e+18,0,14102100,1005,0,543a539e,c7ca3108,3e814130,ecad2386,...,2333,0,39,-1,157,2014-10-21,2014,10,21,0
69999,69999,3.129955e+18,0,14102100,1005,0,5b08c53b,7687a86e,3e814130,ecad2386,...,1994,2,39,-1,33,2014-10-21,2014,10,21,0

In [7]:
a=df.pop('click')
df['click']=a

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 30 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        70000 non-null  int64
 1   id                70000 non-null  float64
 2   hour              70000 non-null  int64
 3   C1                70000 non-null  int64
 4   banner_pos        70000 non-null  int64
 5   site_id           70000 non-null  object
 6   site_domain       70000 non-null  object
 7   site_category     70000 non-null  object
 8   app_id            70000 non-null  object
 9   app_domain        70000 non-null  object
 10  app_category      70000 non-null  object
 11  device_id         70000 non-null  object
 12  device_ip         70000 non-null  object
 13  device_model      70000 non-null  object
 14  device_type       70000 non-null  int64
 15  device_conn_type  70000 non-null  int64
 16  C14               70000 non-null  int64
 17  C15               70000 non-null  int64
 18  C16               70000 non-null  int64
 19  C17               70000 non-null  int64
 20  C18               70000 non-null  int64
 21  C19               70000 non-null  int64
 22  C20               70000 non-null  int64
 23  C21               70000 non-null  int64
 24  tstamp            70000 non-null  datetime64[ns]
 25  year              70000 non-null  int64
 26  month             70000 non-null  int64
 27  day               70000 non-null  int64
 28  hours             70000 non-null  int64
 29  click             70000 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(19), object(9)
memory usage: 16.0+ MB

In [9]:
df=pd.DataFrame(df,columns=['id', 'hour','site_id',
       'site_domain', 'site_category', 'app_id', 'app_domain', 'app_category', 'device_model', 'device_type',
       'device_conn_type','hours', 'banner_pos', 'C1','C14', 'C15', 'C16','C17', 'C18', 'C19', 'C20', 'click'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                70000 non-null  float64
 1   hour              70000 non-null  int64
 2   site_id           70000 non-null  object
 3   site_domain       70000 non-null  object
 4   site_category     70000 non-null  object
 5   app_id            70000 non-null  object
 6   app_domain        70000 non-null  object
 7   app_category      70000 non-null  object
 8   device_model      70000 non-null  object
 9   device_type       70000 non-null  int64
 10  device_conn_type  70000 non-null  int64
 11  hours             70000 non-null  int64
 12  banner_pos        70000 non-null  int64
 13  C1                70000 non-null  int64
 14  C14               70000 non-null  int64
 15  C15               70000 non-null  int64
 16  C16               70000 non-null  int64
 17  C17               70000 non-null  int64
 18  C18               70000 non-null  int64
 19  C19               70000 non-null  int64
 20  C20               70000 non-null  int64
 21  click             70000 non-null  int64
dtypes: float64(1), int64(14), object(7)
memory usage: 11.7+ MB

In [10]:
df.iloc[:,2:12]=df.iloc[:,2:12].astype('category')

In [11]:
for i in range(2,12):
    df.iloc[:,i]=df.iloc[:,i].cat.codes

In [12]:
df

,id,hour,site_id,site_domain,site_category,app_id,app_domain,app_category,device_model,device_type,...,banner_pos,C1,C14,C15,C16,C17,C18,C19,C20,click
0,1.000009e+18,14102100,91,646,2,592,22,0,621,1,...,0,1005,15706,320,50,1722,0,35,-1,0
1,1.000017e+19,14102100,91,646,2,592,22,0,990,1,...,0,1005,15704,320,50,1722,0,35,100084,0
2,1.000037e+19,14102100,91,646,2,592,22,0,1208,1,...,0,1005,15704,320,50,1722,0,35,100084,0
3,1.000064e+19,14102100,91,646,2,592,22,0,874,1,...,0,1005,15706,320,50,1722,0,35,100084,0
4,1.000068e+19,14102100,773,379,0,592,22,0,1045,1,...,1,1005,18993,320,50,2161,0,35,-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,3.129585e+18,14102100,308,47,14,592,22,0,820,1,...,1,1005,16920,320,50,1899,0,431,100081,0
69996,3.129652e+18,14102100,654,404,14,592,22,0,549,1,...,1,1005,17614,320,50,1993,2,1063,100084,1
69997,3.129855e+18,14102100,91,646,2,592,22,0,1070,1,...,0,1005,15706,320,50,1722,0,35,-1,1
69998,3.129902e+18,14102100,275,521,4,592,22,0,855,1,...,0,1005,20352,320,50,2333,0,39,-1,0
69999,3.129955e+18,14102100,293,309,4,592,22,0,1136,1,...,0,1005,17654,300,250,1994,2,39,-1,0

In [13]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [14]:
x

array([[ 1.00000942e+18,  1.41021000e+07,  9.10000000e+01, ...,
         0.00000000e+00,  3.50000000e+01, -1.00000000e+00],
       [ 1.00001693e+19,  1.41021000e+07,  9.10000000e+01, ...,
         0.00000000e+00,  3.50000000e+01,  1.00084000e+05],
       [ 1.00003719e+19,  1.41021000e+07,  9.10000000e+01, ...,
         0.00000000e+00,  3.50000000e+01,  1.00084000e+05],
       ...,
       [ 3.12985466e+18,  1.41021000e+07,  9.10000000e+01, ...,
         0.00000000e+00,  3.50000000e+01, -1.00000000e+00],
       [ 3.12990198e+18,  1.41021000e+07,  2.75000000e+02, ...,
         0.00000000e+00,  3.90000000e+01, -1.00000000e+00],
       [ 3.12995515e+18,  1.41021000e+07,  2.93000000e+02, ...,
         2.00000000e+00,  3.90000000e+01, -1.00000000e+00]])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [17]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [20]:
y_pred = classifier.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.8297142857142857